apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    demo: service
spec:
  # list of containers
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1  # if we did not specify anything, type will be clusterIP.
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    demo: service
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 #container port
