apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    app: nginx-lb
    demo: service
spec:
  # list of containers
  spec: 
  containers:
  - name: nginx-lb
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1  # if we did not specify anything, type will be clusterIP.
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx-lb
    demo: service
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 #container port