apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce   #EBS volume should have readwriteonce, because it HD.
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0faaae6700285753b
# Here we are informing kubernetes, i have this underlying volume created and take this as wrapper
---
#If pods need storage, they need to request or claim.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set. For static provisioning this is empty
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # PV is only 10GB. So we can claim 10GB or less, but not more
---      
# Now attaching to the pod.
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    demo: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html  # where we have to mount
  nodeSelector:
    zone: 1a    
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-static
---
#Adding Service.
apiVersion: v1  # if we did not specify anything, type will be clusterIP.
kind: Service
metadata:
  name: ebs-static
spec:
  type: LoadBalancer
  selector:
    demo: ebs-static
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 #container port
