apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-storageclass
  resources:
    requests:
      storage: 5Gi  # PV is only 10GB. So we can claim 10GB or less, but not more
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    demo: ebs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html  # where we have to mount
  nodeSelector:
    zone: 1a    
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
#Adding Service.
apiVersion: v1  # if we did not specify anything, type will be clusterIP.
kind: Service
metadata:
  name: ebs-dynamic
spec:
  type: LoadBalancer
  selector:
    demo: ebs-static
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 #container port

