apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  #namespace: roboshop # if we did not specify namespace, it will create in default namespace.
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80

